stocks:
  - stock:
      extract:
        stock_ticker: "tsla"
        date_picker: "date_range"
        start_date: "2020-01-01"
        end_date: "2020-01-02"

      load:
        file:
          load_target: "file"
          target_file_directory: "trading_price/data"
          target_file_name: "tesla.parquet"
        database:
          load_target: "database"
          target_table_name: "tesla_stock"

  - stock:
      extract:
        stock_ticker: "aapl"
        date_picker: "date_range"
        start_date: "2020-01-01"
        end_date: "2020-01-02"

      load:
        file:
          load_target: "file"
          target_file_directory: "trading_price/data"
          target_file_name: "apple.parquet"
        database:
          load_target: "database"
          target_table_name: "apple_stock"

  - stock:
      extract:
        stock_ticker: "amzn"
        date_picker: "date_range"
        start_date: "2020-01-01"
        end_date: "2020-01-02"

      load:
        file:
          load_target: "file"
          target_file_directory: "trading_price/data"
          target_file_name: "amazon.parquet"
        database:
          load_target: "database"
